site_name: Python (3 семестр)
site_url: https://kurotych.com/ua/courses/programming-3sem/
repo_url: https://github.com/kurotych/programming-python-3sem
repo_name: kurotych/programming-python-3sem

watch:
  - docs

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

copyright: 2026 Куротич Анатолій. Всі права захищені.

extra:
  analytics:
    provider: google
    property: G-HKDH744EMY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kurotych

nav:
  - Головна: index.md
  - Модуль 1:
    - module1/01-pyside6-intro-lecture.md
    - module1/02-first-pyside6-app-practice.md
    - module1/03-basic-widgets-lecture.md
    - module1/04-input-form-practice.md
    - module1/05-layouts-lecture.md
    - module1/06-adaptive-layout-practice.md
    - module1/07-qmainwindow-lecture.md
    - module1/08-qmainwindow-skeleton-practice.md
    - module1/09-actions-menus-toolbars-lecture.md
    - module1/10-actions-menus-practice.md
